import { BiomeType, CharacterStatType, ItemType, ProfessionType, type ItemDataType } from "./Types";

export const itemDatas: ItemDataType[] = [
  // ===== 任意 (any) =====
  {
    id: 0,
    name: "刺客之刃",
    sourceName: "assassin_blade.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 1,
    name: "血钢肩甲",
    sourceName: "blood_steel_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 2,
    name: "洞察之书",
    sourceName: "book_of_insight.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 3,
    name: "布披肩",
    sourceName: "cloth_cape.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 4,
    name: "铜制头盔",
    sourceName: "copper_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 5,
    name: "铜肩甲",
    sourceName: "copper_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 6,
    name: "龙肉培根",
    sourceName: "dragon_meat_bacon.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 7,
    name: "无尽酒杯",
    sourceName: "endless_goblet.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 8,
    name: "精钢头盔",
    sourceName: "fine_steel_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 9,
    name: "狂怒之锤",
    sourceName: "fury_hammer.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 10,
    name: "黄金盾",
    sourceName: "golden_shield.png",
    itemType: [ItemType.Shield],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 11,
    name: "金矿石",
    sourceName: "gold_ore.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 12,
    name: "骑士头盔",
    sourceName: "knight_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 13,
    name: "骑士肩甲",
    sourceName: "knight_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 14,
    name: "生命之符",
    sourceName: "life_rune.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 15,
    name: "毒药瓶",
    sourceName: "poison_vial.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 16,
    name: "恢复戒指",
    sourceName: "recovery_ring.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 17,
    name: "圣洁法杖",
    sourceName: "sanctified_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 18,
    name: "钨矿石",
    sourceName: "tungsten_ore.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 19,
    name: "战刀",
    sourceName: "war_blade.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 20,
    name: "巫师帽",
    sourceName: "wizard_hat.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 21,
    name: "巫师法杖",
    sourceName: "wizard_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Any],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },

  // ===== 洞穴 (cave) =====
  {
    id: 22,
    name: "护身符",
    sourceName: "amulet.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 23,
    name: "刺客匕首",
    sourceName: "assassin_dagger.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 24,
    name: "刺客兜帽",
    sourceName: "assassin_hood.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 25,
    name: "刺客肩甲",
    sourceName: "assassin_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 26,
    name: "炽焰利刃",
    sourceName: "blazing_blade.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 27,
    name: "黑暗水晶",
    sourceName: "dark_crystal.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 28,
    name: "爆炸箭袋",
    sourceName: "explosive_arrow_quiver.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 29,
    name: "凛风碎石锤",
    sourceName: "frigid_hammer.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 30,
    name: "狂怒之弓",
    sourceName: "fury_bow.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 31,
    name: "狂怒肩甲",
    sourceName: "fury_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 32,
    name: "熔痕匕首",
    sourceName: "molten_dagger.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 33,
    name: "猪肘",
    sourceName: "pork_knuckle.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 34,
    name: "日曜头盔",
    sourceName: "solar_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 35,
    name: "疾行豆",
    sourceName: "swift_bean.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 36,
    name: "迅捷手套",
    sourceName: "swift_gloves.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 37,
    name: "枯萎箭袋",
    sourceName: "withered_arrow_quiver.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Cave],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },

  // ===== 酋长 (chief) =====
  {
    id: 38,
    name: "春分",
    sourceName: "equinox_sword_offhand.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 39,
    name: "火之杖",
    sourceName: "fire_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 40,
    name: "堡垒",
    sourceName: "fortress_shield.png",
    itemType: [ItemType.Shield],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 41,
    name: "月神弓",
    sourceName: "lunar_bow.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief, BiomeType.Ruin],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 42,
    name: "蛇杖",
    sourceName: "serpent_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 43,
    name: "日曜弓",
    sourceName: "solar_bow.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 44,
    name: "至点",
    sourceName: "solstice_sword_main.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 45,
    name: "雷之杖",
    sourceName: "thunder_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 46,
    name: "虚空长剑",
    sourceName: "void_greatsword.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 47,
    name: "水之杖",
    sourceName: "water_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 48,
    name: "白色死神",
    sourceName: "white_reaper.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  // {
  //   id: 49,
  //   name: "白色死神",
  //   sourceName: "white_reaper_offhand.png",
  //   itemType: [ItemType.Weapon],
  //   biomeType: [BiomeType.Chief],
  //   characterStat: [CharacterStatType.Agility],
  //   professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  // },
  {
    id: 50,
    name: "寒冬",
    sourceName: "winter_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 51,
    name: "世界破坏者",
    sourceName: "world_breaker.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Chief],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },

  // ===== 森林 (forest) =====
  {
    id: 52,
    name: "战斧",
    sourceName: "battle_axe.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 53,
    name: "蓝莓",
    sourceName: "blueberry.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 54,
    name: "速度之靴",
    sourceName: "boots_of_speed.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 55,
    name: "百夫长旗帜",
    sourceName: "centurion_banner.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 56,
    name: "百夫长披风",
    sourceName: "centurion_cape.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 57,
    name: "百夫长头盔",
    sourceName: "centurion_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 58,
    name: "德鲁伊兜帽",
    sourceName: "druid_hood.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 59,
    name: "德鲁伊肩垫",
    sourceName: "druid_shoulder_pads.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 60,
    name: "矮人斗篷",
    sourceName: "dwarf_cloak.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 61,
    name: "矮人头盔",
    sourceName: "dwarf_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 62,
    name: "矮人双斧",
    sourceName: "dwarf_twin_axe.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 63,
    name: "热煤块",
    sourceName: "hot_coal.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 64,
    name: "鸮鹦鹉蛋",
    sourceName: "kakapo_egg.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 65,
    name: "鸮鹦鹉之灵",
    sourceName: "kakapo_spirit.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 66,
    name: "橡木棒",
    sourceName: "oak_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 67,
    name: "剃刀戒指",
    sourceName: "razor_ring.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 68,
    name: "泰坦面甲",
    sourceName: "titan_face_guard.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 69,
    name: "泰坦肩甲",
    sourceName: "titan_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 70,
    name: "白色掠夺者斗篷",
    sourceName: "white_raider_cloak.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 71,
    name: "白色掠夺者兜帽",
    sourceName: "white_raider_hood.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 72,
    name: "白色消亡者",
    sourceName: "white_vanquisher.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Forest],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },

  // ===== 冰川 (glacier) =====
  {
    id: 73,
    name: "大天使雕像",
    sourceName: "archangel_statue.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 74,
    name: "巨灵头盔",
    sourceName: "djinn_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 75,
    name: "巨灵肩甲",
    sourceName: "djinn_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 76,
    name: "冰霜护甲",
    sourceName: "frost_armor.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 77,
    name: "冰霜之歌",
    sourceName: "frost_song.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 78,
    name: "冰川冠冕",
    sourceName: "glacier_crown.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 79,
    name: "冰川肩甲",
    sourceName: "glacier_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 80,
    name: "神圣护符",
    sourceName: "holy_amulet.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 81,
    name: "神圣水晶",
    sourceName: "holy_crystal.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 82,
    name: "神圣法杖",
    sourceName: "holy_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 83,
    name: "月神箭袋",
    sourceName: "lunar_arrow_quiver.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 84,
    name: "魔法宝珠",
    sourceName: "magic_orb.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 85,
    name: "救世主",
    sourceName: "savior_shield.png",
    itemType: [ItemType.Shield],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 86,
    name: "稻草人",
    sourceName: "scarecrow_banner.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Glacier],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },

  // ===== 山岳 (mountain) =====
  {
    id: 87,
    name: "希望之旗",
    sourceName: "banner_of_hope.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 88,
    name: "赐福",
    sourceName: "blessing_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 89,
    name: "血腥戒指",
    sourceName: "bloody_ring.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 90,
    name: "壁垒盾",
    sourceName: "bulwark_shield.png",
    itemType: [ItemType.Shield],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 91,
    name: "诅咒挂件",
    sourceName: "cursed_pendant.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 92,
    name: "命运之骰",
    sourceName: "dice_of_fate.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 93,
    name: "狂怒头盔",
    sourceName: "fury_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 94,
    name: "黄金骑士头盔",
    sourceName: "golden_knight_helmet.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 95,
    name: "黄金肩甲",
    sourceName: "golden_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 96,
    name: "黄金矛",
    sourceName: "golden_spear.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Strength],
    professionType: [ProfessionType.Warrior],
  },
  {
    id: 97,
    name: "钢铁之心",
    sourceName: "heart_of_steel.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 98,
    name: "铁钉头槌",
    sourceName: "iron_nail_mace.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 99,
    name: "振奋之旗",
    sourceName: "rallying_banner.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 100,
    name: "圣洁王冠",
    sourceName: "sanctified_crown.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 101,
    name: "圣洁肩甲",
    sourceName: "sanctified_shoulder_armor.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 102,
    name: "荆棘之甲",
    sourceName: "thorns_armor.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 103,
    name: "战旗",
    sourceName: "war_banner.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
  {
    id: 104,
    name: "战锤",
    sourceName: "war_hammer.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Mountain],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },

  // ===== 废墟 (ruin) =====
  {
    id: 105,
    name: "远古之杖",
    sourceName: "ancient_staff.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 106,
    name: "甲虫胸针",
    sourceName: "beetle_brooch.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Knowledge],
    professionType: [ProfessionType.Shaman, ProfessionType.Priest],
  },
  {
    id: 107,
    name: "电之杖",
    sourceName: "lightning_staff.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  // {
  //   id: 108,
  //   name: "月神弓",
  //   sourceName: "lunar_bow.png",
  //   itemType: [ItemType.Weapon],
  //   biomeType: [BiomeType.Ruin],
  //   characterStat: [CharacterStatType.Stamina],
  //   professionType: [ProfessionType.Knight],
  // },
  {
    id: 109,
    name: "月神兜帽",
    sourceName: "lunar_hood.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 110,
    name: "法力操纵器",
    sourceName: "mana_manipulator.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  // {
  //   id: 111,
  //   name: "暗夜兜帽",
  //   sourceName: "night_hood.png",
  //   itemType: [ItemType.Helmet],
  //   biomeType: [BiomeType.Ruin],
  //   characterStat: [CharacterStatType.Intelligence],
  //   professionType: [ProfessionType.Mage],
  // },
  // {
  //   id: 112,
  //   name: "暗夜护肩",
  //   sourceName: "night_shoulder_pads.png",
  //   itemType: [ItemType.ShoulderArmor],
  //   biomeType: [BiomeType.Ruin],
  //   characterStat: [CharacterStatType.Intelligence],
  //   professionType: [ProfessionType.Mage],
  // },
  {
    id: 113,
    name: "日曜箭袋",
    sourceName: "solar_arrow_quiver.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 114,
    name: "风暴之铸",
    sourceName: "storm_forge.png",
    itemType: [ItemType.Weapon],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 115,
    name: "风暴兜帽",
    sourceName: "storm_hood.png",
    itemType: [ItemType.Helmet],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 116,
    name: "风暴护肩",
    sourceName: "storm_shoulder_pads.png",
    itemType: [ItemType.ShoulderArmor],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Intelligence],
    professionType: [ProfessionType.Mage],
  },
  {
    id: 117,
    name: "特斯拉线圈",
    sourceName: "tesla_coil.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Agility],
    professionType: [ProfessionType.Rogue, ProfessionType.Archer],
  },
  {
    id: 118,
    name: "雷霆戒指",
    sourceName: "thunder_ring.png",
    itemType: [ItemType.Artifact],
    biomeType: [BiomeType.Ruin],
    characterStat: [CharacterStatType.Stamina],
    professionType: [ProfessionType.Knight],
  },
];
